services:
  db:
    image: public.ecr.aws/docker/library/postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=juryhack_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Optionnel: gardez le port si vous voulez un accès direct à la DB
    # ports:
    #   - "5434:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=juryhack_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,api.notation.insi.local
      - DJANGO_CACHE_BACKEND=django.core.cache.backends.dummy.DummyCache
    depends_on:
      db:
        condition: service_healthy
    networks:
      - traefik-network
    # Optionnel: gardez le port si vous voulez un accès direct
    # ports:
    #   - "8001:8001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8001"
      - "traefik.http.routers.backend.rule=Host(`api.notation.insi.local`)"
      - "traefik.http.routers.backend.entrypoints=web"
      # Headers anti-cache
      - "traefik.http.middlewares.nocache.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate, max-age=0"
      - "traefik.http.routers.backend.middlewares=nocache"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - traefik-network
    ports:
      - "3333:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.rule=Host(`notation.insi.local`)"
      - "traefik.http.routers.frontend.entrypoints=web"

volumes:
  postgres_data:

networks:
  traefik-network:
    external: true